// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RfidWarehouseApi.Data;

#nullable disable

namespace RfidWarehouseApi.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RfidWarehouseApi.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("CurrentHolderId")
                        .HasColumnType("int")
                        .HasColumnName("current_holder_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("item_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<bool>("ReminderEmailSent")
                        .HasColumnType("bit")
                        .HasColumnName("reminder_email_sent");

                    b.Property<DateTime?>("ReminderEmailSentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reminder_email_sent_at");

                    b.Property<string>("RfidUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("rfid_uid");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ItemId");

                    b.HasIndex("CurrentHolderId");

                    b.HasIndex("RfidUid")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ItemName = "Power Drill",
                            LastUpdated = new DateTime(2026, 1, 2, 16, 37, 11, 709, DateTimeKind.Utc).AddTicks(7593),
                            ReminderEmailSent = false,
                            RfidUid = "RFID001234567890",
                            Status = 0
                        },
                        new
                        {
                            ItemId = 2,
                            ItemName = "Hammer",
                            LastUpdated = new DateTime(2026, 1, 2, 16, 37, 11, 709, DateTimeKind.Utc).AddTicks(7598),
                            ReminderEmailSent = false,
                            RfidUid = "RFID001234567891",
                            Status = 0
                        },
                        new
                        {
                            ItemId = 3,
                            ItemName = "Screwdriver Set",
                            LastUpdated = new DateTime(2026, 1, 2, 16, 37, 11, 709, DateTimeKind.Utc).AddTicks(7600),
                            ReminderEmailSent = false,
                            RfidUid = "RFID001234567892",
                            Status = 0
                        },
                        new
                        {
                            ItemId = 4,
                            ItemName = "Measuring Tape",
                            LastUpdated = new DateTime(2026, 1, 2, 16, 37, 11, 709, DateTimeKind.Utc).AddTicks(7602),
                            ReminderEmailSent = false,
                            RfidUid = "RFID001234567893",
                            Status = 0
                        },
                        new
                        {
                            ItemId = 5,
                            ItemName = "Wrench Set",
                            LastUpdated = new DateTime(2026, 1, 2, 16, 37, 11, 709, DateTimeKind.Utc).AddTicks(7605),
                            ReminderEmailSent = false,
                            RfidUid = "RFID001234567894",
                            Status = 0
                        });
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Administrator with full access",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Regular user with limited access",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Scanner", b =>
                {
                    b.Property<int>("ScannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("scanner_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScannerId"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("ScannerId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Scanner");

                    b.HasData(
                        new
                        {
                            ScannerId = 1,
                            DeviceId = "rpi-scanner-01",
                            Name = "Main Warehouse Entrance",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("action");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ItemId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PinFailedAttempts")
                        .HasColumnType("int")
                        .HasColumnName("pin_failed_attempts");

                    b.Property<string>("PinHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("pin_hash");

                    b.Property<DateTime?>("PinLockoutUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("pin_lockout_until");

                    b.Property<string>("RfidTagUid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("rfid_tag_uid");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RfidTagUid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@warehouse.com",
                            Lastname = "User",
                            Name = "Admin",
                            PasswordHash = "$2a$11$RsgCc9Xu.LyvI2bmCTbnVu/F9YGdBgKddO5rT0FQjvvnqjHSqiX1i",
                            PinFailedAttempts = 0
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john.doe@warehouse.com",
                            Lastname = "Doe",
                            Name = "John",
                            PasswordHash = "$2a$11$7vDI5K4HOL5925bCdxtvueQ6Vo.YEeXyvlPoHlzr1NS42JlxxZXPe",
                            PinFailedAttempts = 0
                        });
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.UserRight", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "user_id,role_id")
                        .IsUnique();

                    b.ToTable("UserRight");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Item", b =>
                {
                    b.HasOne("RfidWarehouseApi.Models.User", "CurrentHolder")
                        .WithMany("Items")
                        .HasForeignKey("CurrentHolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentHolder");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Transaction", b =>
                {
                    b.HasOne("RfidWarehouseApi.Models.Scanner", "Scanner")
                        .WithMany("Transactions")
                        .HasForeignKey("DeviceId")
                        .HasPrincipalKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RfidWarehouseApi.Models.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RfidWarehouseApi.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Scanner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.UserRight", b =>
                {
                    b.HasOne("RfidWarehouseApi.Models.Role", "Role")
                        .WithMany("UserRights")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfidWarehouseApi.Models.User", "User")
                        .WithMany("UserRights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Item", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Role", b =>
                {
                    b.Navigation("UserRights");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Scanner", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.User", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Transactions");

                    b.Navigation("UserRights");
                });
#pragma warning restore 612, 618
        }
    }
}
