// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RfidWarehouseApi.Data;

#nullable disable

namespace RfidWarehouseApi.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RfidWarehouseApi.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("CurrentHolderId")
                        .HasColumnType("int")
                        .HasColumnName("current_holder_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("item_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated");

                    b.Property<string>("RfidUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("rfid_uid");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ItemId");

                    b.HasIndex("CurrentHolderId");

                    b.HasIndex("RfidUid")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ItemName = "Power Drill",
                            LastUpdated = new DateTime(2025, 12, 9, 23, 7, 43, 452, DateTimeKind.Utc).AddTicks(2577),
                            RfidUid = "RFID001234567890",
                            Status = 0
                        },
                        new
                        {
                            ItemId = 2,
                            ItemName = "Hammer",
                            LastUpdated = new DateTime(2025, 12, 9, 23, 7, 43, 452, DateTimeKind.Utc).AddTicks(2579),
                            RfidUid = "RFID001234567891",
                            Status = 0
                        },
                        new
                        {
                            ItemId = 3,
                            ItemName = "Screwdriver Set",
                            LastUpdated = new DateTime(2025, 12, 9, 23, 7, 43, 452, DateTimeKind.Utc).AddTicks(2581),
                            RfidUid = "RFID001234567892",
                            Status = 0
                        },
                        new
                        {
                            ItemId = 4,
                            ItemName = "Measuring Tape",
                            LastUpdated = new DateTime(2025, 12, 9, 23, 7, 43, 452, DateTimeKind.Utc).AddTicks(2582),
                            RfidUid = "RFID001234567893",
                            Status = 0
                        },
                        new
                        {
                            ItemId = 5,
                            ItemName = "Wrench Set",
                            LastUpdated = new DateTime(2025, 12, 9, 23, 7, 43, 452, DateTimeKind.Utc).AddTicks(2583),
                            RfidUid = "RFID001234567894",
                            Status = 0
                        });
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Scanner", b =>
                {
                    b.Property<int>("ScannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("scanner_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScannerId"));

                    b.Property<string>("DeviceIdString")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id_string");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location_name");

                    b.HasKey("ScannerId");

                    b.HasIndex("DeviceIdString")
                        .IsUnique();

                    b.ToTable("Scanners");

                    b.HasData(
                        new
                        {
                            ScannerId = 1,
                            DeviceIdString = "rpi-scanner-01",
                            LocationName = "Main Warehouse Entrance"
                        });
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("action");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ItemId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RfidTagUid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("rfid_tag_uid");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RfidTagUid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@warehouse.com",
                            Lastname = "User",
                            Name = "Admin",
                            PasswordHash = "$2a$11$zSORvuaSdTGCnZrKnqMIqevxhWgClBa/1cBWEUAYYssz3wZmME8Ai",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john.doe@warehouse.com",
                            Lastname = "Doe",
                            Name = "John",
                            PasswordHash = "$2a$11$x5y0/osEkY8EWBICD455nuB1lK/41fin0Yet1sPNk1eAaiJdEvpLK",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Item", b =>
                {
                    b.HasOne("RfidWarehouseApi.Models.User", "CurrentHolder")
                        .WithMany("Items")
                        .HasForeignKey("CurrentHolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentHolder");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Transaction", b =>
                {
                    b.HasOne("RfidWarehouseApi.Models.Scanner", "Scanner")
                        .WithMany("Transactions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RfidWarehouseApi.Models.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RfidWarehouseApi.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Scanner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Item", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.Scanner", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RfidWarehouseApi.Models.User", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
